{
 "title": "Solar Panel Dashboard",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "host",
    "query": "SHOW TAG VALUES WITH KEY = \"host\""
   }
  ]
 },
 "panels": [
  {
   "title": "PV Watt",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "Solar",
     "query": "SELECT last(\"AC_Watt\") FROM \"Solar\" WHERE time > now() - 5m GROUP BY \"host\"",
     "select": [
      [
       { "params": [ "AC_Watt" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "PV Power",
   "type": "graph",
   "gridPos": { "h": 14, "w": 20, "x": 4, "y": 0 },
   "yaxes": [
    { "format": "watt" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Solar",
     "select": [
      [
       { "params": [ "AC_Watt" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total production today",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "kwatth" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "measurement": "Solar",
     "query": "select sum(Total) from (SELECT last(\"day_yield\") as Total FROM \"Solar\" WHERE  $timeFilter group by host)",
     "select": [
      [
       { "params": [ "day_yield" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "SMA" }
     ]
    }
   ]
  },
  {
   "title": "PV Voltage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "alias": "$col $tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Solar",
     "select": [
      [
       { "params": [ "DC_Volt_A" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "DC_A_Voltage" ], "type": "alias" }
      ],
      [
       { "params": [ "DC_Volt_B" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "DC_B_Voltage" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "DC Ampere",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "alias": "$tag_host $col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Solar",
     "select": [
      [
       { "params": [ "DC_Amps_A" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "DC A" ], "type": "alias" }
      ],
      [
       { "params": [ "DC_Amps_B" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "DC B" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Production last year",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "kwatth" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "query": "SELECT max(\"day_yield\") FROM \"Solar\" WHERE $timeFilter GROUP BY time($__interval), host fill(none) TZ('Europe/Amsterdam')"
    }
   ]
  },
  {
   "title": "Wh distribution",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "query": "SELECT max(\"AC_Watt\") FROM \"Solar\" WHERE (\"host\" = '${host}') AND AC_Watt > 0 AND $timeFilter GROUP BY time($__interval) fill(none)"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "Solar",
     "select": [
      [
       { "params": [ "Temp" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Leakage",
   "type": "graph",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "mamp" }
   ],
   "targets": [
    {
     "alias": "$tag_host leak",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "Solar",
     "query": "SELECT max(\"leakage\") *1000 FROM \"Solar\" WHERE  $timeFilter GROUP BY host, time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "leakage" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "*1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "SMA" }
     ]
    }
   ]
  }
 ]
}